"""Tạo bảng topics, subjects, và topic_subject 

Revision ID: b7c5355757ee
Revises: dc3c6cde8f0d
Create Date: 2024-08-15 17:03:13.107063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7c5355757ee'
down_revision = 'dc3c6cde8f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('topic_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_subject', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('topic_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
