"""Tạo bảng topics, subjects, và topic_subject

Revision ID: dc3c6cde8f0d
Revises: e5e750e651b1
Create Date: 2024-08-15 16:49:30.546505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc3c6cde8f0d'
down_revision = 'e5e750e651b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])
        batch_op.drop_column('topic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
