"""Add topics and subjects tables 

Revision ID: e5e750e651b1
Revises: 44dcfb73b341
Create Date: 2024-08-15 12:02:01.861186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e750e651b1'
down_revision = '44dcfb73b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_subject', schema=None) as batch_op:
        batch_op.drop_constraint('topic_subject_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('topic_subject_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topic_subject_ibfk_2', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('topic_subject_ibfk_1', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
